### PR TITLE
added swagger, postgress and env config

### PR DESCRIPTION
**Pull request by sommy-josh**

### CODE REVIEW

**Review by successmasodi — CHANGES_REQUESTED** [review]
dont push images to remote (github)
also in your settings.py after setting your debug to environmental variable, dont set it to true again (remove ==True)

**Comment by sommy-josh** [comment]
oh okay.

**Comment by successmasodi** [comment]
great!

**Review by successmasodi — APPROVED** [review]
great
learn class based view tho. it makes life easier😉

**Pull request merged**
